name: Test aur-maintainer

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: soker90/aur-maintainer@v1
        with:
          github-token: ${{ secrets.MAN_TOKEN }}
          update-branch: update
          base-branch: master
          auto-merge: false
          aur-publish: false
